### PR TITLE
Adding tasks_by_priority parameter to TaskQStat response

### PR DESCRIPTION
**Pull request by wanjunsli**
GET request to TaskQueue, Workflow and Workspace Statistics will have a field "tasks_by_priority" under RealTime Stats, similar to the "tasks_by_status" field. 

Example: 
"tasks_by_priority": {"5":1}

### CODE REVIEW

**Comment by jingming** [comment]
do you have to add fields to the models as well?

**Comment by wanjunsli** [comment]
Yes, sorry. Will add those.

**Comment by jingming** [comment]
+1

**Comment by jingming** [comment]
Closing due to `5.0.0` release.

**Pull request closed without merging**
