### PR TITLE
Prevent WebRequestClient from hiding network errors

### PR DESCRIPTION
**Pull request by adamtal3**
Fixes twilio/twilio-csharp#361

This prevents a NullReferenceException being thrown instead of WebException (in case of 400 Bad Request or invalid SSL/TLS settings) + showing the network error as the inner exception of TwilioException

### CODE REVIEW

**Comment by jmctwilio** [comment]
@adamtal3 

Could you walk me through why you'd make the proposed changes to the WebException block of MakeRequest?  If I understand correctly, we don't want to lose the original WebException -- that would happen if any of the code in HandleErrorResponse raised an exception (like the NullReferenceException).

The pattern in the WebException handler looks odd.  Could we accomplish the same thing by adding some additional error handling in HandleErrorResponse itself to just raise the `innerException` if it fails to construct the appropriate TwilioException?

**Comment by adamtal3** [comment]
@jmctwilio - I agree the pattern is a bit odd, but it should cover any possible issue with the error handling (from the Response conversion to any issue inside `HandleErrorResponse`).
This code helped me after 20 days of not knowing why my SMS sending suddenly fails.

The original code failed for me because of some edge case the programmer didn't think about writing the error handler function. I didn't want to make the same mistake.. I think it should avoid hiding the real exception as it can cause too much trouble (we faced it only in production)

Do you have a more elegant solution in mind?

**Comment by jmctwilio** [comment]
@adamtal3 - You make a good point about wanting to avoid missing some unexpected edge case as clearly was done before (costing you a lot of time and effort!).  There are pros and cons to adding the additional try/catch block in both places.  Your point is certainly valid and on the other side of things, I can see wanting to make `HandleErrorResponse` more robust so every future case doesn't have to worry about wrapping it.

I'll talk over the two strategies with the team and get one of them committed as soon as we're able.  Thanks for sharing your thoughts and for helping make the code better!

**Comment by jmctwilio** [comment]
#373

**Pull request closed without merging**
