### PR TITLE
chore: Added a Dockerfile to be able to easily build and test.

### PR DESCRIPTION
**Pull request by marcusber**
# Fixes #

Adds a Dockerfile for building and testing the solution. Makes the solution more accessible for contributing developers.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-csharp/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
  * Tests passes using the instruction in the readme.
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified
  * No code modifled.

### CODE REVIEW

**Comment by JenniferMah** [comment]
Hi @marcusber, 
Could you clarify you mean when you said `dotnet build does not work and make does not exist.` Are you not able to run tests locally with the `make test` command?

**Comment by marcusber** [comment]
@JenniferMah Of course.
In the existing Dockerfile in the repo with the commands I provided above it did not build (several errors and tons of warnings) and make was not installed on that image. 

When it comes to my local computer I do not have all those legacy frameworks installed, so using Docker was easier for me. So, no, it did not build on my local installation of VS2022 (net6 and some more, but not enough to build the repo). Also, I don't have make on my windows machine.

The Dockerfile in this PR installs all that. Building as well as all tests works (both using dotnet build and make). Using the commands in the README.md you could build and update the code in the repo, without being forced to rebuild the docker-image after every update.
It still gives up a ton of warnings, mostly due to malformed documentation.

Sorry about the confusion.

**Comment by childish-sambino** [comment]
I'm in favor of merging the changes into the existing Dockerfile. I can test afterwards in our internal process to make sure everything still works properly.

One thing we do need for the internal process is the steps:
```docker
COPY src ./src
COPY test ./test
COPY Twilio.sln .
```
We want to ensure we have the source in the image (instead of coming from a mounted volume).

This should still work with your documentation additions as you can still mount the volume for more rapid local development; it will just either reside alongside or replace the `/twilio` contents in the running container.

Let me know if more clarification is needed.

**Comment by marcusber** [comment]
Closed in favor of https://github.com/twilio/twilio-csharp/pull/623

**Pull request closed without merging**
