### PR TITLE
Add beta and preview attributes

### PR DESCRIPTION
**Pull request by ilanbiala**

### CODE REVIEW

**Comment by efossier** [comment]
What does this end up looking like to the end user?

**Comment by ilanbiala** [comment]
Classes that are beta/preview will have an annotation that denotes this. I'm not sure if that makes it into whatever docs we generate though.

**Comment by efossier** [comment]
I mean what does this.Text end up doing? does it show up in generated docs? in the IDE?

**Comment by ilanbiala** [comment]
@efossier It seems like this doesn't show up in generated docs. I don't think it shows up in most IDEs except maybe C# ones such as Visual Studio?

**Comment by ilanbiala** [comment]
Unnecessary.

**Pull request closed without merging**
