### PR TITLE
Add Ci and fix unit tests

### PR DESCRIPTION
**Pull request by mplacona**
Hey, just adding some Ci integration and fixing some of the broken unit tests

### CODE REVIEW

**Comment by mplacona** [comment]
Oh, I will change the URL for the CI badge once this gets reviewed and merged

**Comment by carlosdp** [comment]
Can you just change the url now?

**Comment by mplacona** [comment]
Not without having my changes merged. It doesn't even build otherwise.

You can check it on my fork though.

Can you just change the url now?

—
Reply to this email directly or view it on GitHub
<https://github.com/twilio/twilio-csharp/pull/187#issuecomment-148779141>.

**Comment by mplacona** [comment]
Updated the badge

**Comment by carlosdp** [comment]
:+1:

**Pull request merged**
